# Use a Node base image
FROM node:14-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the rest of your frontend application
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Command to start the app
CMD ["npm", "start"]
