"""Add missing columns

Revision ID: 24cb754f0a9a
Revises: None
Create Date: 2024-05-05 22:45:00.170581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cb754f0a9a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
